config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :links do
  		put "like", to:"links#upvote"
   		put "dislike", to:"links#downvote"
  	end
  root to: "links#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
	acts_as_votable
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
        has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!,except: [:index, :show]
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
    @link =Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end
  def downvote
    @link =Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:link, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RadditClone</title>
    <%= csrf_meta_tags %>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"type="text/javascript"></script>
  <link href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.2/chosen.jquery.min.js" type="text/javascript"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.2/chosen.css" rel="stylesheet" />
  <href src ="https://cdnjs.cloudflare.com/ajax/libs/font-mfizz/2.4.1/font-mfizz.min.css" rel="stylesheet" />
</head>

<div class="container">
<nav class="navbar navbar-default" style ="background-color: #80d0c7 ">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
   <!--    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    --> <div id ="logo" class="navbar-brand" ><%= link_to "Reddit",links_path %> </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav"> -->
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
         <!  </ul>
        </li>
      </ul> -->
       <% if user_signed_in?%>
      <ul class="nav navbar-nav navbar-left">
        <li> <%= link_to "Add article",new_link_path %></li>
      </ul>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#">Link</a></li> -->
          <%if user_signed_in? %>
            <li><%=link_to "Account settings ",edit_user_registration_path %></li>
            <li><%= link_to "Logout" ,destroy_user_session_path,method: :delete %><li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path%></li>
            <li><%= link_to "Register", new_user_registration_path %></li>
  		  <% end %>
      </ul>
    <!-- </div>/.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% if notice %>
    <div class="alert alert-success"><%= notice %>
    </div>
  <%end%>
  <% if alert %> 
       <div class="alert alert-danger"><%= alert %>
       </div>
       <%end%>
    <%= yield %>
    </div><body id ="back">
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Title %>
    <%= form.text_field :link, id: :link_link,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url%>
    <%= form.text_field :url, id: :link_url,class: "form-control" %>
  </div>

  <div class="actions ">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<!-- <div class="jumbotron text-center">
  <h1>Links lists</h1>
</div>
 -->    <% @links.each do |link| %>
     <h3><%= link_to link.link,link %></h3>
     <h6>Submitted <%= time_ago_in_words(link.created_at) %> earlier by <%= link.user.email %></h6>
     
    <% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<h1><%= @link.link %></h1>
<h5>Submitted <%= time_ago_in_words(@link.created_at) %> earlier by <%= @link.user.email %></h5>
<h5><%=link_to "Go to Website", @link.url ,class: "btn btn-primary"%></h5>
 <% if user_signed_in? %>
<% if @link.user_id == current_user.id %>
	<div class="btn btn-group">
        <%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default"  %>
 <% end %>
</div>
<% end %>
 <div class="btn-group">
 	<a class="btn btn-default" href= "<%= @link.url %>">Visit Links </a>
 	<%= link_to link_like_path(@link),:data => {:method => :put},class: "btn btn-default" do %>
 	<span class="glyphicon glyphicon-chevron-up"></span>
 	upvote
 	<%= @link.get_upvotes.size %>
  <%end%>

 <%= link_to link_dislike_path(@link),method: :put,class: "btn btn-default" do %>
 	<span class="glyphicon glyphicon-chevron-down"></span>
 	downvote
 	<%= @link.get_downvotes.size %>         
 	<% end %>
 	</div>